version: 2.1
orbs:
    slack: circleci/slack@4.3.0
    
workflows:
    version: 2.1
    build-deploy:
        jobs:
        - build
        - deploy:
            requires:
                - build
            filters:
                branches:
                    only: master

jobs:
  build:
    docker:
    - image: circleci/ruby:2.6.5-node-browsers
      environment:
        - BUNDLER_VERSION: 2.1.4
        - RAILS_ENV: 'test'

    - image: circleci/mysql:5.6
      environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        - MYSQL_ROOT_HOST: '127.0.0.1'

    working_directory: ~/sample_app

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "Gemfile.lock" }}
        - v1-dependencies-


    - run:
        name: install dependencies
        command: |
          gem install bundler -v 2.1.4
          bundle install --jobs=4 --retry=3 --path vendor/bundle
    - save_cache:
        paths:
        - ./vendor/bundle
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}


    # database setup
    - run: mv ./config/database.yml.ci ./config/database.yml

    # database setup
    - run:
        name: setup database
        command: |
           bundle exec rake db:create
           bundle exec rake db:schema:load

    # install yarn
    - run:
        name: install yarn
        command: yarn install


    #run rubocop
    - run:
        name: Rubocop
        command: |
            bundle exec rubocop -A
            bundle exec rubocop -a
            bundle exec rubocop 

    - run:
        name: Chrome Driver Install
        command: chromedriver
        background: true

    # run tests
    - run:
        name: run rspec
        command: bundle exec rspec

    # collect reports
    - store_test_results:
        path: /tmp/test-results

    - store_artifacts:
        path: /tmp/test-results
        destination: test-results

    - slack/notify:
        event: fail
        mentions: '@togo_mori'
        template: basic_fail_1
    - slack/notify:
        event: pass
        mentions: '@togo_mori'
        template: basic_success_1

  deploy:
    docker:
        - image: circleci/ruby:2.6.5-node-browsers
          environment:
              BUNDLER_VERSION: 2.1.4
    steps:
        - checkout
        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
        - run:
            name: install dependencies
            command: |
                gem install bundler -v 2.1.4
                bundle install --jobs=4 --retry=3 --path vendor/bundle
        - save_cache:
            paths:
            - ./vendor/bundle
            key: v1-dependencies-{{ checksum "Gemfile.lock" }}
        - add_ssh_keys:
            fingerprints: "8c:79:ba:1a:0b:a1:db:04:05:60:07:e5:0f:f8:a4:e7"
        - run:
            name: Unicorn stop
            command: |
                bundle exec cap production unicorn:stop
        - run:
            name: Capistrano deploy
            command: |
                bundle exec cap production deploy
        - slack/notify:
            event: fail
            mentions: '@togo_mori'
            template: basic_fail_1
        - slack/notify:
            event: pass
            mentions: '@togo_mori'
            template: success_tagged_deploy_1